#
# Copyright (c) 2019 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

# ubinos_config_info {"name_base": "ubik_tester", "build_type": "cmake_ubinos", "app": true}

set_cache(UBINOS__BSP__LINKSCRIPT_FILE "${PROJECT_UBINOS_DIR}/source/ubinos/bsp/arch/arm/cortexm/nrf52/xxaa/flash_bdh.ld" PATH)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_DMPM FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_DMPM_DIR_ON_OFF FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_DMPM_MEMORY_READY_CHECK FALSE BOOL)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BESTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__FIRSTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__NEXTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__PGROUP FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__GROUP FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BBUDDY FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__WBUDDY FALSE BOOL)

# set_cache(UBINOS__UBICLIB__HEAP_DIR0_ALGORITHM "GROUP" STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_LOCKTYPE "MUTEX" STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_M 8 STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLCOUNT 226 STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLBM_BUFSIZE 36 STRING)

set_cache(UBINOS__UBICLIB__HEAP_DIR0_ALGORITHM "BESTFIT" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_LOCKTYPE "MUTEX" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_M 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLCOUNT 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLBM_BUFSIZE 4 STRING)

set_cache(UBINOS__UBICLIB__HEAP_DIR1_ALGORITHM "BESTFIT" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_LOCKTYPE "MUTEX" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_M 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_FBLCOUNT 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_FBLBM_BUFSIZE 4 STRING)

set_cache(UBINOS__UBICLIB__HEAP_DEFAULT_DIR 1 STRING)
set_cache(UBINOS__UBICLIB__HEAP_ALIGNMENT 16 STRING)

# set_cache(UBINOS__BSP__STACK_SIZE 0x12000 STRING)

include(${CMAKE_CURRENT_LIST_DIR}/ubik_tester_nrf52840dk_rtctick.cmake)

